let cars = [
  "BMW M3",
  "Audi A4",
  "Mercedes C-Class",
  "Toyota Fortuner",
  "Honda City",
  "Hyundai Creta",
  "Tata Nexon",
  "Mahindra Thar",
  "Kia Seltos",
  "Maruti Swift",

  "BMW M3",
  "Audi Q5",
  "Mercedes GLC",
  "Toyota Camry",
  "Honda Civic",
  "Hyundai Verna",
  "Tata Harrier",
  "Mahindra XUV700",
  "Kia Sonet",
  "Maruti Baleno",

  "Toyota Fortuner",
  "BMW X5",
  "Audi A6",
  "Mercedes E-Class",
  "Honda City",
  "Hyundai Venue",
  "Tata Punch",
  "Mahindra Scorpio",
  "Kia Carens",
  "Maruti Brezza",

  "BMW X3",
  "Audi A4",
  "Mercedes C-Class",
  "Toyota Innova",
  "Honda Amaze",
  "Hyundai Creta",
  "Tata Nexon",
  "Mahindra Thar",
  "Kia Seltos",
  "Maruti Swift",

  "BMW M4",
  "Audi Q7",
  "Mercedes GLE",
  "Toyota Camry",
  "Honda Elevate",
  "Hyundai i20",
  "Tata Harrier",
  "Mahindra XUV700",
  "Kia Sonet",
  "Maruti Baleno",

  "BMW X5",
  "Audi A6",
  "Mercedes E-Class",
  "Toyota Innova",
  "Honda City",
  "Hyundai Verna",
  "Tata Punch",
  "Mahindra Scorpio",
  "Kia Carens",
  "Maruti Brezza",

  "BMW M3",
  "Audi Q5",
  "Mercedes GLC",
  "Toyota Fortuner",
  "Honda Amaze",
  "Hyundai Venue",
  "Tata Nexon",
  "Mahindra Thar",
  "Kia Seltos",
  "Maruti Swift",

  "BMW X3",
  "Audi A4",
  "Mercedes C-Class",
  "Toyota Camry",
  "Honda Civic",
  "Hyundai Creta",
  "Tata Harrier",
  "Mahindra XUV700",
  "Kia Sonet",
  "Maruti Baleno",

  "BMW M4",
  "Audi Q7",
  "Mercedes GLE",
  "Toyota Innova",
  "Honda City",
  "Hyundai Verna",
  "Tata Punch",
  "Mahindra Scorpio",
  "Kia Carens",
  "Maruti Brezza",

  "BMW X5",
  "Audi A6",
  "Mercedes E-Class",
  "Toyota Fortuner",
  "Honda Elevate",
  "Hyundai Venue",
  "Tata Nexon",
  "Mahindra Thar",
  "Kia Seltos",
  "Maruti Swift"
];

console.log(cars);

let new = [...new set(cars)];
console.log(new);

